services:
  database:
    image: postgis/postgis:15-3.4
    ports:
      - "7676:5432"
    networks:
      - app-network
    environment:
      POSTGRES_USER: directus
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: directus
    volumes:
      - ./data/database:/var/lib/postgresql/data:z
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U directus"]
      interval: 10s
      timeout: 5s
      retries: 5

  directus:
    build: 
      context: .
    ports:
      - "7777:8055"
    networks:
      - app-network
    depends_on:
      database:
        condition: service_healthy
    environment:
      ADMIN_EMAIL: "${DIRECTUS_ADMIN_EMAIL:-admin@event.com}"
      ADMIN_PASSWORD: "${DIRECTUS_ADMIN_PASSWORD}"
      KEY: "${DIRECTUS_KEY}"
      SECRET: "${DIRECTUS_SECRET}"
      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "${DB_PASSWORD}"
      WEBSOCKETS_ENABLED: "true"
      CORS_ENABLED: "true"
      CORS_ORIGIN: "${CORS_ORIGIN:-http://localhost:3000,http://localhost:3001}"
      CORS_METHODS: "GET,POST,PATCH,DELETE"
      CORS_ALLOWED_HEADERS: "Content-Type,Authorization"
      PROJECT_NAME: "IPB-LSA"
    volumes:
      - ./uploads:/directus/uploads:z
      - ./extensions:/directus/extensions:z

networks:
  app-network:
    driver: bridge